
const htmlFerias = `

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<TITLE>nathan testes</TITLE>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
</HEAD><BODY>
<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 COLS=37>
<TR>
	<TD WIDTH=0 HEIGHT=5></TD>
	<TD WIDTH=4 HEIGHT=1></TD>
	<TD WIDTH=1 HEIGHT=1></TD>
	<TD WIDTH=5 HEIGHT=1></TD>
	<TD WIDTH=0 HEIGHT=1></TD>
	<TD WIDTH=2 HEIGHT=1></TD>
	<TD WIDTH=0 HEIGHT=1></TD>
	<TD WIDTH=67 HEIGHT=1></TD>
	<TD WIDTH=6 HEIGHT=1></TD>
	<TD WIDTH=53 HEIGHT=1></TD>
	<TD WIDTH=8 HEIGHT=1></TD>
	<TD WIDTH=35 HEIGHT=1></TD>
	<TD WIDTH=94 HEIGHT=1></TD>
	<TD WIDTH=42 HEIGHT=1></TD>
	<TD WIDTH=33 HEIGHT=1></TD>
	<TD WIDTH=5 HEIGHT=1></TD>
	<TD WIDTH=4 HEIGHT=1></TD>
	<TD WIDTH=13 HEIGHT=1></TD>
	<TD WIDTH=9 HEIGHT=1></TD>
	<TD WIDTH=51 HEIGHT=1></TD>
	<TD WIDTH=8 HEIGHT=1></TD>
	<TD WIDTH=3 HEIGHT=1></TD>
	<TD WIDTH=2 HEIGHT=1></TD>
	<TD WIDTH=95 HEIGHT=1></TD>
	<TD WIDTH=7 HEIGHT=1></TD>
	<TD WIDTH=11 HEIGHT=1></TD>
	<TD WIDTH=26 HEIGHT=1></TD>
	<TD WIDTH=0 HEIGHT=1></TD>
	<TD WIDTH=4 HEIGHT=1></TD>
	<TD WIDTH=43 HEIGHT=1></TD>
	<TD WIDTH=5 HEIGHT=1></TD>
	<TD WIDTH=16 HEIGHT=1></TD>
	<TD WIDTH=77 HEIGHT=1></TD>
	<TD WIDTH=2 HEIGHT=1></TD>
	<TD WIDTH=0 HEIGHT=1></TD>
	<TD WIDTH=2 HEIGHT=1></TD>
	<TD WIDTH=4 HEIGHT=1></TD>
	<TD HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=33></TD>
	<TD ROWSPAN=57></TD>
	<TD COLSPAN=34 ALIGN=CENTER><B><FONT FACE=Arial>RECIBO DE FÉRIAS</FONT></B></TD>
	<TD COLSPAN=2 ROWSPAN=3></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=34 ALIGN=CENTER><FONT SIZE=-2 FACE=Arial>De acordo com o Parágrafo Único do Artigo 145 da C.L.T</FONT></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=34></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=3 ROWSPAN=19></TD>
	<TD COLSPAN=6><FONT SIZE=-1 FACE=Arial>Nome Empresa: </FONT></TD>
	<TD COLSPAN=26 ROWSPAN=2><FONT SIZE=-1 FACE=Arial>INDÚSTRIA E COMÉRCIO DE COLCHÕES TORAFLEX LTDA</FONT></TD>
	<TD ROWSPAN=57></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=6 ROWSPAN=2></TD>
</TR>

<TR>
	<TD HEIGHT=4></TD>
	<TD COLSPAN=26 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=6><FONT SIZE=-1 FACE=Arial>Nome Empregado: </FONT></TD>
	<TD COLSPAN=26 ROWSPAN=2><FONT SIZE=-1 FACE=Arial>ADIVALDO LIMA DOS SANTOS</FONT></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=6 ROWSPAN=2></TD>
</TR>

<TR>
	<TD HEIGHT=5></TD>
	<TD COLSPAN=26 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=6><FONT SIZE=-1 FACE=Arial>Centro de Custo: </FONT></TD>
	<TD COLSPAN=26 ROWSPAN=2><FONT SIZE=-1 FACE=Arial>PORTARIA</FONT></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=6 ROWSPAN=2></TD>
</TR>

<TR>
	<TD HEIGHT=4></TD>
	<TD COLSPAN=26 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=6><FONT SIZE=-1 FACE=Arial>Departamento: </FONT></TD>
	<TD COLSPAN=26 ROWSPAN=2><FONT SIZE=-1 FACE=Arial>PORTARIA</FONT></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=6 ROWSPAN=2></TD>
</TR>

<TR>
	<TD HEIGHT=5></TD>
	<TD COLSPAN=26 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=6><FONT SIZE=-1 FACE=Arial>Cargo: </FONT></TD>
	<TD COLSPAN=26 ROWSPAN=2><FONT SIZE=-1 FACE=Arial>VIGIA</FONT></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=6 ROWSPAN=2></TD>
</TR>

<TR>
	<TD HEIGHT=5></TD>
	<TD COLSPAN=26 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=6><FONT SIZE=-1 FACE=Arial>Cart. Trabalho:</FONT></TD>
	<TD COLSPAN=15 ROWSPAN=2><FONT SIZE=-1 FACE=Arial>0794675 / 00040</FONT></TD>
	<TD COLSPAN=4 ALIGN=RIGHT><FONT SIZE=-1 FACE=Arial>Nº Registro:</FONT></TD>
	<TD ROWSPAN=3></TD>
	<TD COLSPAN=6 ROWSPAN=2><FONT SIZE=-1 FACE=Arial>000766</FONT></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=6 ROWSPAN=3></TD>
	<TD COLSPAN=4 ROWSPAN=2></TD>
</TR>

<TR>
	<TD HEIGHT=4></TD>
	<TD COLSPAN=15 HEIGHT=1></TD>
	<TD COLSPAN=6 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=1></TD>
	<TD COLSPAN=26 ROWSPAN=2><FONT SIZE=-1 FACE=Arial>10/05/2017 à 09/05/2018</FONT></TD>
</TR>

<TR>
	<TD HEIGHT=18></TD>
	<TD COLSPAN=2 ROWSPAN=18></TD>
	<TD COLSPAN=7 ROWSPAN=2><FONT SIZE=-1 FACE=Arial>Período de Aquisição: </FONT></TD>
</TR>

<TR>
	<TD HEIGHT=1></TD>
	<TD COLSPAN=26 ROWSPAN=2></TD>
</TR>

<TR>
	<TD HEIGHT=4></TD>
	<TD COLSPAN=7 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD ROWSPAN=15></TD>
	<TD COLSPAN=6><FONT SIZE=-1 FACE=Arial>Período de Gozo: </FONT></TD>
	<TD COLSPAN=26 ROWSPAN=2><FONT SIZE=-1 FACE=Arial>20/12/2018 à 18/01/2019</FONT></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=6 ROWSPAN=2></TD>
</TR>

<TR>
	<TD HEIGHT=5></TD>
	<TD COLSPAN=26 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=32><FONT SIZE=-1 FACE=Arial>Período de Abono:</FONT></TD>
</TR>

<TR>
	<TD HEIGHT=4></TD>
	<TD COLSPAN=32 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=6><FONT SIZE=-1 FACE=Arial>Data de Retorno: </FONT></TD>
	<TD COLSPAN=26 ROWSPAN=2><FONT SIZE=-1 FACE=Arial>21/01/2019</FONT></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=6 ROWSPAN=2></TD>
</TR>

<TR>
	<TD HEIGHT=14></TD>
	<TD COLSPAN=26 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=1></TD>
	<TD COLSPAN=3 ROWSPAN=2><B><FONT SIZE=-1 FACE=Arial>SALÁRIO: </FONT></B></TD>
	<TD COLSPAN=4 ROWSPAN=3><B><FONT SIZE=-1 FACE=Arial>1.120,64</FONT></B></TD>
	<TD ROWSPAN=2><B><FONT SIZE=-1 FACE=Arial>+ COMP. SAL.:</FONT></B></TD>
	<TD COLSPAN=6 ROWSPAN=3><B><FONT SIZE=-1 FACE=Arial>0,00</FONT></B></TD>
	<TD COLSPAN=3 ROWSPAN=2><B><FONT SIZE=-1 FACE=Arial>+ MÉDIA: </FONT></B></TD>
	<TD COLSPAN=3 ROWSPAN=3><B><FONT SIZE=-1 FACE=Arial>90,15</FONT></B></TD>
	<TD COLSPAN=6 HEIGHT=1></TD>
	<TD COLSPAN=6 ROWSPAN=3><B><FONT SIZE=-1 FACE=Arial>1.210,79</FONT></B></TD>
</TR>

<TR>
	<TD HEIGHT=18></TD>
	<TD COLSPAN=6 ROWSPAN=3><B><FONT SIZE=-1 FACE=Arial>= SAL. BASE: </FONT></B></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=3 HEIGHT=1></TD>
	<TD HEIGHT=1></TD>
	<TD COLSPAN=3 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=3 ROWSPAN=2><B><FONT SIZE=-1 FACE=Arial>FALTAS: </FONT></B></TD>
	<TD COLSPAN=17 ROWSPAN=3><B><FONT SIZE=-1 FACE=Arial>0</FONT></B></TD>
	<TD COLSPAN=6 ROWSPAN=4></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=6 ROWSPAN=3></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=3 ROWSPAN=2></TD>
</TR>

<TR>
	<TD HEIGHT=7></TD>
	<TD COLSPAN=17 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=14></TD>
	<TD ROWSPAN=17></TD>
	<TD COLSPAN=12 HEIGHT=1 ALIGN=CENTER><B><FONT SIZE=-1 FACE=Arial>Evento</FONT></B></TD>
	<TD ROWSPAN=2></TD>
	<TD COLSPAN=5 HEIGHT=1 ALIGN=CENTER><B><FONT SIZE=-1 FACE=Arial>Referência</FONT></B></TD>
	<TD COLSPAN=7 HEIGHT=1 ALIGN=RIGHT><B><FONT SIZE=-1 FACE=Arial>Vencimentos</FONT></B></TD>
	<TD COLSPAN=6 HEIGHT=1 ALIGN=RIGHT><B><FONT SIZE=-1 FACE=Arial>Descontos</FONT></B></TD>
	<TD COLSPAN=3 ROWSPAN=8></TD>
</TR>

<TR>
	<TD HEIGHT=10></TD>
	<TD COLSPAN=12 HEIGHT=1></TD>
	<TD COLSPAN=18 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=3 ROWSPAN=6></TD>
	<TD COLSPAN=11><FONT SIZE=-1 FACE=Arial>0020 - Férias</FONT></TD>
	<TD COLSPAN=3 ALIGN=RIGHT><FONT SIZE=-1 FACE=Arial>30,00</FONT></TD>
	<TD COLSPAN=9 ALIGN=RIGHT><FONT SIZE=-1 FACE=Arial>1.210,79</FONT></TD>
	<TD COLSPAN=5 ROWSPAN=4></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=23 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=18><FONT SIZE=-1 FACE=Arial>0021 - 1/3 Abono Obrigatório Férias</FONT></TD>
	<TD COLSPAN=5 ALIGN=RIGHT><FONT SIZE=-1 FACE=Arial>403,60</FONT></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=23 HEIGHT=1></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=11><FONT SIZE=-1 FACE=Arial>0520 - Desconto INSS</FONT></TD>
	<TD COLSPAN=3 ALIGN=RIGHT><FONT SIZE=-1 FACE=Arial>8,00</FONT></TD>
	<TD COLSPAN=13 ALIGN=RIGHT><FONT SIZE=-1 FACE=Arial>129,15</FONT></TD>
	<TD ROWSPAN=2></TD>
</TR>

<TR>
	<TD HEIGHT=60></TD>
	<TD COLSPAN=27></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=2 ROWSPAN=9></TD>
	<TD COLSPAN=18><FONT SIZE=-1 FACE=Arial>T O T A I S: </FONT></TD>
	<TD COLSPAN=4 ROWSPAN=2 ALIGN=RIGHT><FONT SIZE=-1 FACE=Arial>1.614,39</FONT></TD>
	<TD COLSPAN=8 ROWSPAN=2 ALIGN=RIGHT><FONT SIZE=-1 FACE=Arial>129,15</FONT></TD>
	<TD COLSPAN=2 ROWSPAN=3></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=18 ROWSPAN=2></TD>
</TR>

<TR>
	<TD HEIGHT=24></TD>
	<TD COLSPAN=12></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=5 ROWSPAN=2><B><FONT SIZE=-1 FACE=Arial>SALÁRIO LÍQUIDO: </FONT></B></TD>
	<TD COLSPAN=27><B><FONT SIZE=-1 FACE=Arial>1.485,24</FONT></B></TD>
</TR>

<TR>
	<TD HEIGHT=0></TD>
	<TD COLSPAN=27 ROWSPAN=2></TD>
</TR>

<TR>
	<TD HEIGHT=24></TD>
	<TD COLSPAN=5></TD>
</TR>

<TR>
	<TD HEIGHT=85></TD>
	<TD COLSPAN=2 ROWSPAN=3></TD>
	<TD COLSPAN=30 VALIGN=TOP><FONT SIZE=-1 FACE=Arial>Recebi da firma INDÚSTRIA E COMÉRCIO DE COLCHÕES TORAFLEX LTDA estabelecida à Rodovia Avenida<BR>Amazonas, 1700 - em Betim  a importância de R$ 1.485,24 (Um Mil  Quatrocentos e Oitenta e Cinco Reais  e Vinte e<BR>Quatro Centavos) que me é paga conforme prazo estipulado em lei. Por motivo das minhas férias regulamentares, ora<BR>concedidas e que vou gozar de acordo com a descriçäo acima, tudo conforme o aviso que recebi em tempo, ao qual dei<BR>meu ciente.<BR></FONT></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=30><FONT SIZE=-1 FACE=Arial>Para clareza e documento, firmo o presente recibo, dando a firma plena e geral quitaçäo.</FONT></TD>
</TR>

<TR>
	<TD HEIGHT=75></TD>
	<TD COLSPAN=30></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=36 ALIGN=CENTER><FONT SIZE=-1 FACE=Arial>Betim, ______ de ______________________ de __________ .</FONT></TD>
</TR>

<TR>
	<TD HEIGHT=57></TD>
	<TD COLSPAN=36></TD>
</TR>

<TR>
	<TD HEIGHT=19></TD>
	<TD COLSPAN=8></TD>
	<TD COLSPAN=23 ALIGN=CENTER VALIGN=TOP><FONT SIZE=-1 FACE=Arial>ADIVALDO LIMA DOS SANTOS</FONT></TD>
	<TD COLSPAN=5></TD>
</TR>
</TABLE>

</BODY></HTML>

`

export default htmlFerias
